language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- bash sharik/tests/test_cli.sh
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Zt1xISJUMrNqsXMw4adJrJAKk6ZBkRKMR2yb67v7xyeFtY6RuP1t16LmKulcAwVGZrxpJNgHKF5Xc64ZotfwvIfnoqr0gnrGe6j67Hb1fiFnKAkb+qhks16DUhCehEPbrkvwZggH3jS9PGwa0nhBaisI5cLglE6hmStPh07CCosSkfe4hVT7m36yLfuoQf4ILl+ztDiB3DA6xfftnsM0rJl2w1pw9+LjFkGpx54KKtIwZpJZJWNnDZBr4Dn4DwUcJKpaSb+HTMwe2UxsJ3boY+D1yyseeFDcrITnqtfxwFfCsZahbd/pkHHMsyNXXNsL+ZgUvHIM13z+2rrUC7MoPF8pIFd5hsk7FmeU0qY0OyVsAQvO6cijrKcGa4SP9LGFw6Rwgf+r4PvTgLtfDfujCtD34hdOPbs9hCu95enV8OX0JlOK7eiMuMsJ1pU60UYegzKuycGRkmPvZTxieSxrclkhmHCNysp1mNvhhUBWwtWdxA41KrbM1CPTPTcLQ90U7xZG1HHjICj+e/SON0vHW0kJLBu9RTtsoXa6WC/6L3cPUHq/LaLA09HkII3HvXJvrreEs02tSymEZLEM/R1ueHD8Qwc42VT6VN7KSzXeyNNXmUY2hbTR4cB9I3Qh4zciWrN/ENEhDoZpWOENpqAnud1jQzZvDqRFSCqDBzH+xpE=
