language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - bash sharik/tests/test_cli.sh
  - pytest

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: QoAtCmT4njdTOTTSZ1Kc1BtaW3oGyL8cX96/v+4SVPipNZMNS7Cbx7FXI1L0YLEA+HKvx/8tZlRjYeewgqWa3PFHl5vHZHI8cqzfBq9KG8U0p7O/b9SA448vfG2H8weDXpNX30SKqA/xUGyY0OJMFwTffMzPPfrd4EMlGtWXrQnJZD4dv4WQ8CrzsF41L18mrxYVrduM6JdTiBkodmaKMnsypfyRefAi9Y1xV8XY7aALB3OPJhnUoq9wrB3XR/ploKv0B7UNn63nEZeKkyQ3xz9ssHF8qVhdUjYYIxIEZ3rDGUoBQP/GFejeSgNdPvFxiKOedM8JmnFWOO8NoUYXxnBHfjtqTA7CsdeOvypszCVekpMFTOVxfVU8rmMvf/W1nAJDBroREn/+dlgcFnqYuq1W5Q05Wc3CkTg0CjV8CThvSaA8caGYK8gHDaJwsPDvQrgi9ngsA3+pTxZJtB9ZTP1PxxQiB7r0kAltSmxFvQXPboAR222Sf/eoH9D82w/zxYfqB28wdicJx7EjQRrSMtSE08/hnv9qMYVhfi1JRzsdQwp05YDgOdaHSVqN7eZgipnp/D+oJh3pcCJm5Q6zyrXnDXJ7WJNh0gzdZA3ef/Bq6cnBxDzjWXC4PQhp97YY8Qjcpbw9I8XNt/HGFWXrJdt5TtfvOCfbZoEDI5kGQDU=
